language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -e .
  - pip install coveralls
script:
  - python setup.py test -a "--cov gfit2mfp tests"
after_success:
    coveralls
