language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install -e .
  - pip install coveralls
  - pip install codecov
script:
  - python setup.py test -a "--cov gfit2mfp"
after_success:
  - coveralls
  - codecov
