language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
    - pip install .
    - pip install coverage coveralls
# command to run tests
script:
    - coverage run --source=gfit2mfp setup.py test
after_success:
    coveralls --verbose
