language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -e .
  - pip install coverage coveralls
script:
  - coverage run --source=gfit2mfp setup.py test --pytest-args=tests
after_success:
    coveralls
